"use client";
import { useCallback, useEffect, useMemo, useState } from "react";
import { supabase } from "@/lib/supabase";
import type { Order } from "@/lib/types";

type DeliveryOrder=Order&{delivery_slot?:string;batch_label?:string;fulfillment_type?:string;source?:string};
const mapFromNotes=(notes:string|null)=>notes?.match(/Customer map:\s*(https?:\/\/\S+)/i)?.[1]||"";
function Copy({value,label}:{value:string;label:string}){const [done,setDone]=useState(false);return <button disabled={!value} onClick={async()=>{await navigator.clipboard.writeText(value);setDone(true);setTimeout(()=>setDone(false),1200)}}>{done?"✓ Copied":`Copy ${label}`}</button>}
export default function DeliveryPage(){const [orders,setOrders]=useState<DeliveryOrder[]>([]),[loading,setLoading]=useState(true),[date,setDate]=useState("");const load=useCallback(async()=>{setLoading(true);const{data}=await supabase.from("orders").select("*").eq("fulfillment_type","delivery").neq("status","cancelled").order("delivery_date").order("delivery_slot");setOrders((data||[]) as DeliveryOrder[]);setLoading(false)},[]);useEffect(()=>{load()},[load]);const dates=useMemo(()=>Array.from(new Set(orders.map(o=>o.delivery_date).filter(Boolean))) as string[],[orders]);const shown=orders.filter(o=>(!date||o.delivery_date===date)&&o.status!=="dispatched");return <main className="delivery-board"><header><div><span>🚚</span><div><h1>Delivery details</h1><p>{shown.length} delivery{shown.length===1?"":"ies"} ready</p></div></div><button onClick={load}>↻ Refresh</button></header><div className="delivery-filters"><button className={!date?"active":""} onClick={()=>setDate("")}>All</button>{dates.map(d=><button className={date===d?"active":""} key={d} onClick={()=>setDate(d)}>{new Date(d+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"short"})}</button>)}</div>{loading?<p className="delivery-empty">Loading deliveries…</p>:shown.length===0?<p className="delivery-empty">No pending deliveries.</p>:<div className="delivery-list">{shown.map(o=>{const map=mapFromNotes(o.notes);const all=[o.customer_name,o.phone||"",o.address||"",map].filter(Boolean).join("\n");return <article key={o.id}><div className="delivery-card-title"><div><small>{o.delivery_date} · {o.delivery_slot||o.batch_label||"Time not set"}</small><h2>{o.customer_name}</h2><p>{o.source==="trivandrum"?"🚂 TVM":"🍡 Kochi"}</p></div><Copy value={all} label="all details"/></div><div className="delivery-detail"><span>Name</span><strong>{o.customer_name}</strong><Copy value={o.customer_name} label="name"/></div><div className="delivery-detail"><span>Phone</span><strong>{o.phone||"—"}</strong><Copy value={o.phone||""} label="phone"/></div><div className="delivery-detail"><span>Address</span><strong>{o.address||"—"}</strong><Copy value={o.address||""} label="address"/></div><div className="delivery-detail"><span>Google Maps</span><strong>{map||"—"}</strong><Copy value={map} label="map"/></div>{map&&<a href={map} target="_blank" rel="noreferrer">Open in Google Maps →</a>}</article>})}</div>}</main>}
