"use client";
import { useState } from "react";
import type { Product } from "@/lib/types";

export function FlavourSettingsModal({products,onClose,onChanged}:{products:Product[];onClose:()=>void;onChanged:()=>Promise<void>}){
  const[name,setName]=useState(""),[busy,setBusy]=useState(""),[error,setError]=useState("");
  async function add(){const value=name.trim();if(!value)return;setBusy("add");setError("");try{const response=await fetch("/api/admin/flavours",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:value})}),data=await response.json();if(!response.ok)throw new Error(data.error);setName("");await onChanged()}catch(caught){setError(caught instanceof Error?caught.message:"Could not add flavour")}finally{setBusy("")}}
  async function remove(product:Product){if(!window.confirm(`Remove ${product.name} from the available flavours?\n\nExisting orders will keep their history.`))return;setBusy(product.id);setError("");try{const response=await fetch("/api/admin/flavours",{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({id:product.id,name:product.name})}),data=await response.json();if(!response.ok)throw new Error(data.error);await onChanged()}catch(caught){setError(caught instanceof Error?caught.message:"Could not remove flavour")}finally{setBusy("")}}
  return <div className="order-modal-backdrop" onClick={event=>{if(event.target===event.currentTarget)onClose()}}><section className="flavour-settings"><header><div><small>SETTINGS</small><h2>Manage flavours</h2><p>Add or remove flavours shown to customers.</p></div><button onClick={onClose}>✕</button></header><div className="add-flavour-row"><input value={name} onChange={event=>setName(event.target.value)} onKeyDown={event=>{if(event.key==="Enter")add()}} placeholder="New flavour name"/><button disabled={!name.trim()||Boolean(busy)} onClick={add}>{busy==="add"?"Adding…":"＋ Add"}</button></div>{error&&<p className="modal-error">{error}</p>}<div className="settings-flavour-list">{products.map(product=><div key={product.id}><span>{product.name}</span><button disabled={Boolean(busy)} onClick={()=>remove(product)}>{busy===product.id?"Removing…":"Remove"}</button></div>)}</div></section></div>;
}
