"use client";
import { useMemo, useState } from "react";
import type { Product, BoxSize } from "@/lib/types";
import type { ExtOrder } from "../_lib/constants";

const TIMES=["9–11 AM","11 AM–1 PM","1–3 PM","3–5 PM","5–7 PM","7–9 PM","9–11 PM"];
const mapFromNotes=(notes?:string|null)=>notes?.match(/Customer map:\s*(https?:\/\/\S+)/i)?.[1]||"";

function CopyField({label,value,onChange,area=false}:{label:string;value:string;onChange:(value:string)=>void;area?:boolean}){
  const[copied,setCopied]=useState(false);
  async function copy(){if(!value)return;await navigator.clipboard.writeText(value);setCopied(true);setTimeout(()=>setCopied(false),1200)}
  return <label className="copy-field"><span>{label}<button type="button" onClick={copy}>{copied?"✓ Copied":"Copy"}</button></span>{area?<textarea rows={2} value={value} onChange={event=>onChange(event.target.value)}/>:<input value={value} onChange={event=>onChange(event.target.value)}/>}</label>;
}

export function OrderManagerModal({order,products,boxes,password,onClose,onSaved,onDeleted}:{order:ExtOrder|null;products:Product[];boxes:BoxSize[];password:string;onClose:()=>void;onSaved:()=>void;onDeleted:()=>void}){
  const[form,setForm]=useState({customer_name:order?.customer_name||"",phone:order?.phone||"",address:order?.address||"",customer_maps_url:mapFromNotes(order?.notes),delivery_date:order?.delivery_date||"",delivery_slot:order?.delivery_slot||order?.batch_label||"",box_size_id:order?.box_size_id||"",location:order?.source==="trivandrum"?"trivandrum":"kochi",fulfillment_type:order?.fulfillment_type||"delivery",status:order?.status||"confirmed",total_price:String(order?.total_price||""),flavours:order?.flavours||{} as Record<string,number>});
  const[saving,setSaving]=useState(false),[deleting,setDeleting]=useState(false),[error,setError]=useState(""),[flavourSearch,setFlavourSearch]=useState("");
  const set=(key:string,value:string)=>setForm(current=>({...current,[key]:value}));
  const quantity=(id:string,delta:number)=>setForm(current=>{const flavours={...current.flavours},next=Math.max(0,(flavours[id]||0)+delta);if(next)flavours[id]=next;else delete flavours[id];return{...current,flavours}});
  const selectedPieces=Object.values(form.flavours).reduce((sum,count)=>sum+count,0);
  const visibleProducts=useMemo(()=>products.filter(product=>product.name.toLowerCase().includes(flavourSearch.trim().toLowerCase())).sort((a,b)=>a.name.localeCompare(b.name,undefined,{sensitivity:"base"})),[products,flavourSearch]);

  async function invoice(){
    const names=products.filter(product=>form.flavours[product.id]).map(product=>`${form.flavours[product.id]}× ${product.name}`).join(", ")||"Flavours to be confirmed";
    const number=`EVS-${new Date().toISOString().slice(0,10).replace(/-/g,"")}-${order?.id.slice(0,6).toUpperCase()}`;
    const canvas=document.createElement("canvas"),scale=2,width=720,height=900;canvas.width=width*scale;canvas.height=height*scale;const context=canvas.getContext("2d")!;context.scale(scale,scale);context.fillStyle="#fffdf8";context.fillRect(0,0,width,height);context.fillStyle="#c99545";context.fillRect(0,0,width,14);context.fillStyle="#3b2114";context.textAlign="center";context.font="bold 42px Georgia";context.fillText("EVERSWEET",width/2,78);context.font="16px Georgia";context.fillText("HAPPINESS IN ONE BITE",width/2,108);context.strokeStyle="#d9bd91";context.beginPath();context.moveTo(55,140);context.lineTo(width-55,140);context.stroke();context.textAlign="left";context.font="bold 17px system-ui";context.fillText("INVOICE",55,186);context.textAlign="right";context.font="14px system-ui";context.fillText(number,width-55,184);context.textAlign="left";
    const rows=[["Customer",form.customer_name],["Phone",form.phone],["Delivery",`${form.delivery_date} · ${form.delivery_slot}`],["Location",form.location==="trivandrum"?"Trivandrum":"Kochi"],["Address",form.address||"—"],["Flavours",names]];let y=235;for(const[label,value]of rows){context.fillStyle="#826c60";context.font="13px system-ui";context.fillText(label.toUpperCase(),55,y);context.fillStyle="#3b2114";context.font="16px system-ui";const lines=value.match(/.{1,65}(?:\s|$)/g)||[value];lines.forEach((line,index)=>context.fillText(line.trim(),190,y+index*24));y+=Math.max(52,lines.length*24+20)}context.strokeStyle="#d9bd91";context.beginPath();context.moveTo(55,620);context.lineTo(width-55,620);context.stroke();context.font="bold 18px system-ui";context.fillText("TOTAL",55,670);context.textAlign="right";context.font="bold 28px system-ui";context.fillText(`₹${Number(form.total_price||0).toLocaleString("en-IN")}`,width-55,672);context.textAlign="center";context.font="15px system-ui";context.fillStyle="#826c60";context.fillText("Thank you for choosing Eversweet 🍡",width/2,790);context.fillStyle="#c99545";context.fillRect(0,height-14,width,14);
    const blob=await new Promise<Blob|null>(resolve=>canvas.toBlob(resolve,"image/png",1));if(!blob)return;const file=new File([blob],`eversweet-invoice-${number}.png`,{type:"image/png"});if(navigator.share&&navigator.canShare?.({files:[file]})){await navigator.share({files:[file],title:`Eversweet invoice ${number}`})}else{const url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=file.name;anchor.click();URL.revokeObjectURL(url)}
  }
  async function save(){if(!form.customer_name.trim()||!form.phone.trim()||!form.delivery_date||!form.delivery_slot){setError("Please enter name, phone, date and time.");return}setSaving(true);setError("");try{const response=await fetch("/api/admin/orders",{method:order?"PATCH":"POST",headers:{"Content-Type":"application/json","x-admin-password":password},body:JSON.stringify({...form,id:order?.id})}),data=await response.json();if(!response.ok)throw new Error(data.error);onSaved()}catch(caught){setError(caught instanceof Error?caught.message:"Could not save order")}finally{setSaving(false)}}
  async function remove(){if(!order||!window.confirm(`Delete ${order.customer_name}'s order?\n\nIt will disappear from the calendar.`))return;setDeleting(true);setError("");try{const response=await fetch("/api/admin/orders",{method:"DELETE",headers:{"Content-Type":"application/json","x-admin-password":password},body:JSON.stringify({id:order.id})}),data=await response.json();if(!response.ok)throw new Error(data.error);onDeleted()}catch(caught){setError(caught instanceof Error?caught.message:"Could not delete order")}finally{setDeleting(false)}}

  return <div className="order-modal-backdrop" onClick={event=>{if(event.target===event.currentTarget)onClose()}}><div className="order-modal">
    <header><div><small>{order?"EDIT ORDER":"NEW ORDER"}</small><h2>{order?order.customer_name:"Add an order"}</h2></div><button onClick={onClose}>✕</button></header>
    <div className="order-modal-grid"><CopyField label="Name" value={form.customer_name} onChange={value=>set("customer_name",value)}/><CopyField label="Phone" value={form.phone} onChange={value=>set("phone",value)}/><label><span>Date</span><input type="date" value={form.delivery_date} onChange={event=>set("delivery_date",event.target.value)}/></label><label><span>Time</span><select value={form.delivery_slot} onChange={event=>set("delivery_slot",event.target.value)}><option value="">Choose time</option>{TIMES.map(time=><option key={time}>{time}</option>)}</select></label></div>
    <label><span>Box size</span><select value={form.box_size_id} onChange={event=>set("box_size_id",event.target.value)}><option value="">Choose box size</option>{boxes.filter(box=>box.is_active).map(box=><option key={box.id} value={box.id}>{box.label} · {box.count} pieces</option>)}</select></label>
    <div className="location-toggle">{[["kochi","🍡 Kochi"],["trivandrum","🚂 TVM"]].map(([value,label])=><button type="button" className={form.location===value?"active":""} key={value} onClick={()=>set("location",value)}>{label}</button>)}</div>
    <div className="location-toggle">{[["delivery","🚚 Delivery"],["pickup","🏠 Pickup"]].map(([value,label])=><button type="button" className={form.fulfillment_type===value?"active":""} key={value} onClick={()=>set("fulfillment_type",value)}>{label}</button>)}</div>
    <CopyField label="Address" value={form.address} onChange={value=>set("address",value)} area/><CopyField label="Google Maps link" value={form.customer_maps_url} onChange={value=>set("customer_maps_url",value)}/>
    <div className="modal-flavours"><div className="modal-flavour-heading"><span>Flavours</span><b>{selectedPieces} pieces selected</b></div>{selectedPieces>0&&<div className="modal-selected-flavours">{products.filter(product=>form.flavours[product.id]).map(product=><button type="button" key={product.id} onClick={()=>quantity(product.id,-form.flavours[product.id])}><b>{form.flavours[product.id]}</b>{product.name}<span>×</span></button>)}</div>}<input className="modal-flavour-search" type="search" value={flavourSearch} onChange={event=>setFlavourSearch(event.target.value)} placeholder="Search flavours…"/><div className="modal-flavour-list">{visibleProducts.map(product=><div className={`modal-flavour-qty ${form.flavours[product.id]?"selected":""}`} key={product.id}><span>{product.name}</span><button type="button" onClick={()=>quantity(product.id,-1)}>−</button><b>{form.flavours[product.id]||0}</b><button type="button" onClick={()=>quantity(product.id,1)}>+</button></div>)}{visibleProducts.length===0&&<p className="no-flavour-results">No matching flavour</p>}</div></div>
    {order&&<div className="order-modal-grid"><label><span>Status</span><select value={form.status} onChange={event=>set("status",event.target.value)}>{["confirmed","cooking","cooked","dispatched"].map(status=><option key={status}>{status}</option>)}</select></label><label><span>Price</span><input type="number" value={form.total_price} onChange={event=>set("total_price",event.target.value)}/></label></div>}
    {error&&<p className="modal-error">{error}</p>}
    <div className="modal-actions">{order&&<button type="button" className="delete-order-action" disabled={deleting||saving} onClick={remove}>{deleting?"Deleting…":"Delete order"}</button>}{order&&<button type="button" className="invoice-action" onClick={invoice}>🧾 Generate invoice</button>}<button type="button" className="modal-save" disabled={saving||deleting} onClick={save}>{saving?"Saving…":order?"Save order":"Add order"}</button></div>
  </div></div>;
}
