"use client";
import { useEffect, useMemo, useState } from "react";

type Product={id:string;name:string}; type Box={id:string;label:string;count:number};
type PlannedBox={key:string;box_size_id:string;flavours:Record<string,number>};
type Form={customer_name:string;phone:string;address:string;customer_maps_url:string;delivery_date:string;delivery_slot:string};
const TIMES=["9–11 AM","11 AM–1 PM","1–3 PM","3–5 PM","5–7 PM","7–9 PM","9–11 PM"];
const FALLBACK_FLAVOURS=["Mango","Strawberry","Blueberry","Red Cherry","Lemon Curd","Kiwi","Green Apple","Orange","Pear","Nutella","Milk Choco Nuts","Coffee Nuts","Biscoff","Dark Chocolate","Pistachio","Hazelnut","Pomegranate"].map(name=>({id:name.toLowerCase().replace(/\s+/g,"-"),name}));
const initial:Form={customer_name:"",phone:"",address:"",customer_maps_url:"",delivery_date:"",delivery_slot:""};

export default function NewConfirmationPage(){
 const[form,setForm]=useState(initial),[products,setProducts]=useState<Product[]>([]),[boxes,setBoxes]=useState<Box[]>([]),[plan,setPlan]=useState<PlannedBox[]>([]);
 const[activeKey,setActiveKey]=useState(""),[search,setSearch]=useState(""),[error,setError]=useState(""),[orderId,setOrderId]=useState(""),[saving,setSaving]=useState(false),[step,setStep]=useState(1);
 useEffect(()=>{fetch("/api/order-confirmation").then(async r=>{const d=await r.json();if(!r.ok)throw new Error(d.error);return d}).then(d=>{const list=d.products?.length?d.products:FALLBACK_FLAVOURS;setProducts([...list].sort((a:Product,b:Product)=>a.name.localeCompare(b.name)));setBoxes(d.boxes||[])}).catch(()=>setError("Box sizes and flavours could not be loaded. Please refresh and try again."))},[]);
 const visible=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(search.trim().toLowerCase())),[products,search]);
 const active=plan.find(b=>b.key===activeKey)||plan[0], activeSize=boxes.find(b=>b.id===active?.box_size_id);
 const used=(b?:PlannedBox)=>b?Object.values(b.flavours).reduce((a,n)=>a+n,0):0, activeUsed=used(active);
 const total=plan.reduce((n,b)=>n+used(b),0),required=plan.reduce((n,b)=>n+(boxes.find(x=>x.id===b.box_size_id)?.count||0),0);
 const update=(key:keyof Form,value:string)=>setForm(f=>({...f,[key]:value}));
 const moveTo=(n:number)=>{setError("");setStep(n);requestAnimationFrame(()=>window.scrollTo({top:0,behavior:"smooth"}))};
 const addBox=(box:Box)=>{const key=`${box.id}-${Date.now()}-${plan.length}`;setPlan(p=>[...p,{key,box_size_id:box.id,flavours:{}}]);setActiveKey(key);setSearch("")};
 const removeBox=(key:string)=>setPlan(current=>{const next=current.filter(b=>b.key!==key);if(key===activeKey)setActiveKey(next[0]?.key||"");return next});
 const changeFlavour=(id:string,delta:number)=>{if(!active||!activeSize)return;setPlan(current=>current.map(box=>{if(box.key!==active.key)return box;const count=used(box);if(delta>0&&count>=activeSize.count)return box;const flavours={...box.flavours},next=Math.max(0,(flavours[id]||0)+delta);if(next)flavours[id]=next;else delete flavours[id];return{...box,flavours}}))};
 const aggregate=()=>plan.reduce<Record<string,number>>((all,box)=>{Object.entries(box.flavours).forEach(([id,n])=>all[id]=(all[id]||0)+n);return all},{});
 const continueBoxes=()=>{if(!plan.length){const m="Please add at least one box.";setError(m);alert(m);return}const incomplete=plan.find(b=>used(b)!==(boxes.find(x=>x.id===b.box_size_id)?.count||0));if(incomplete){const m=`Please finish Box ${plan.indexOf(incomplete)+1} before continuing.`;setActiveKey(incomplete.key);setError(m);alert(m);return}moveTo(2)};
 const continueDetails=()=>{if(!form.customer_name.trim()||!form.phone.trim()||!form.delivery_date||!form.delivery_slot){const m="Please enter your name, phone number, delivery date and time.";setError(m);alert(m);return}moveTo(3)};
 async function submit(e:React.FormEvent){e.preventDefault();setError("");setSaving(true);try{const same=plan.every(b=>b.box_size_id===plan[0]?.box_size_id);const body={...form,box_selections:plan.map(({box_size_id,flavours})=>({box_size_id,flavours})),box_size_id:plan[0]?.box_size_id||"",box_quantity:same?plan.length:1,flavours:aggregate()};const r=await fetch("/api/order-confirmation",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)}),d=await r.json();if(!r.ok)throw new Error(d.error);setOrderId(d.id);window.scrollTo({top:0})}catch(e){setError(e instanceof Error?e.message:"Could not save your details")}finally{setSaving(false)}}
 if(orderId)return <main className="confirm-page"><div className="confirm-card confirmation-done"><div className="done-icon">✓</div><p className="section-label">ORDER RECEIVED</p><h1>Thank you, {form.customer_name.split(" ")[0]}!</h1><p>Your details are now on Eversweet’s calendar.</p><a className="confirm-submit edit-link" href={`/confirm/${orderId}`}>View or edit my details</a></div></main>;
 return <main className="confirm-page"><form className="confirm-card" onSubmit={submit}>
  <div className="confirm-hero"><span>🍡</span><div><p>Payment complete?</p><h1>Confirm your order details</h1></div></div>
  <div className="confirm-steps">{[{n:1,label:"Boxes"},{n:2,label:"Details"},{n:3,label:"Delivery"}].map(x=><div className={`${step===x.n?"active":""} ${step>x.n?"done":""}`} key={x.n}><b>{step>x.n?"✓":x.n}</b><span>{x.label}</span></div>)}</div>
  <p className="confirm-note">{step===1?"Build each box and choose the exact number of every flavour.":step===2?"Now tell us who the order is for and when you need it.":"Finally, add the delivery details."}</p>
  {step===1&&<div className="confirm-step-panel"><section className="box-choice-section"><h2>Add a box</h2><div className="box-choice-grid">{[4,5,6,8].map(size=>{const box=boxes.find(b=>b.count===size);return <button type="button" disabled={!box} key={size} onClick={()=>box&&addBox(box)}><b>＋ {size}</b><small>piece box</small></button>})}</div></section>
   {plan.length>0&&<section className="box-builder"><div className="box-tabs">{plan.map((box,i)=>{const size=boxes.find(b=>b.id===box.box_size_id),count=used(box);return <button type="button" className={box.key===active?.key?"active":""} onClick={()=>setActiveKey(box.key)} key={box.key}><small>BOX {i+1}</small><b>{size?.count} pieces</b><span className={count===size?.count?"complete":""}>{count}/{size?.count}</span></button>})}</div>
    {active&&activeSize&&<><div className="active-box-heading"><div><small>NOW FILLING</small><h2>Box {plan.indexOf(active)+1} · {activeSize.count} pieces</h2></div><button type="button" onClick={()=>removeBox(active.key)}>Remove</button></div>
     {activeUsed>0&&<div className="selected-flavour-chips chosen-box"><b>IN THIS BOX</b>{products.filter(p=>active.flavours[p.id]).map(p=><button type="button" onClick={()=>changeFlavour(p.id,-1)} key={p.id}><strong>{active.flavours[p.id]}×</strong>{p.name}<span>−</span></button>)}</div>}
     <div className="flavour-tools"><input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search flavours…"/><span className={activeUsed===activeSize.count?"complete":""}>{activeUsed}/{activeSize.count}</span></div>
     <div className="flavour-grid flavour-quantity-grid">{visible.map((p,i)=>{const qty=active.flavours[p.id]||0;return <div className={`flavour-choice tone-${i%5} ${qty?"checked":""}`} key={p.id}><span>{p.name}</span><div className="flavour-piece-stepper"><button type="button" disabled={!qty} onClick={()=>changeFlavour(p.id,-1)}>−</button><b>{qty}</b><button type="button" disabled={activeUsed>=activeSize.count} onClick={()=>changeFlavour(p.id,1)}>＋</button></div></div>})}</div>{!visible.length&&<p className="no-flavour-results">No matching flavour</p>}</>}
   </section>}
   {plan.length>0&&<div className="box-plan-total"><b>{plan.length} box{plan.length===1?"":"es"}</b><span>{total}/{required} pieces arranged</span></div>}{error&&<div className="confirm-error">{error}</div>}<div className="step-actions one"><button type="button" className="confirm-submit" onClick={continueBoxes}>Continue</button></div></div>}
  {step===2&&<div className="confirm-step-panel"><section><h2>When should we prepare it?</h2><div className="confirm-grid"><label><span>Name</span><input value={form.customer_name} onChange={e=>update("customer_name",e.target.value)} placeholder="Your name"/></label><label><span>Phone number</span><input inputMode="tel" value={form.phone} onChange={e=>update("phone",e.target.value)} placeholder="Your phone number"/></label><label><span>Date</span><input type="date" value={form.delivery_date} onChange={e=>update("delivery_date",e.target.value)}/></label><label><span>Time</span><select value={form.delivery_slot} onChange={e=>update("delivery_slot",e.target.value)}><option value="">Choose a time</option>{TIMES.map(t=><option key={t}>{t}</option>)}</select></label></div></section>{error&&<div className="confirm-error">{error}</div>}<div className="step-actions"><button type="button" className="step-back" onClick={()=>moveTo(1)}>Back</button><button type="button" className="confirm-submit" onClick={continueDetails}>Continue</button></div></div>}
  {step===3&&<div className="confirm-step-panel"><section><h2>Where should it go?</h2><label><span>Address</span><textarea rows={3} value={form.address} onChange={e=>update("address",e.target.value)} placeholder="House, street, area and landmark"/></label><label><span>Google Maps location link</span><input type="url" value={form.customer_maps_url} onChange={e=>update("customer_maps_url",e.target.value)} placeholder="Paste the shared map link"/></label><p className="field-help">In Google Maps, tap Share → Copy link, then paste it here.</p></section>{error&&<div className="confirm-error">{error}</div>}<div className="step-actions"><button type="button" className="step-back" onClick={()=>moveTo(2)}>Back</button><button className="confirm-submit" disabled={saving}>{saving?"Saving your order…":"Confirm my order"}</button></div></div>}
 </form></main>
}
